<?php
/**
 * @var $block \Briqpay\Checkout\Block\Adminhtml\Payment\Checkout\Info
 */
?>
<div class="order-payment-method-name"><?= $block->escapeHtml($block->getMethod()->getTitle()); ?></div>
<table class="data-table admin__table-secondary">
    <tr>
        <th><?= $block->escapeHtml(__('Briqpay Purchase ID')); ?>:</th>
        <td><?= $block->escapeHtml($block->getBriqpayPurchaseId()); ?></td>
    </tr>
    <tr>
        <th><?= $block->escapeHtml(__('Briqpay Payment Method')); ?>:</th>
        <td><?= $block->escapeHtml($block->getBriqpayPaymentMethod()); ?></td>
    </tr>
</table>
