<?php
// @codingStandardsIgnoreFile
/** @var $block \Briqpay\Checkout\Block\Checkout\Order\Success */
$realId = $block->getRealOrderId();
?>

<div class="checkout-success" id="briqpay-checkout-success">
    <?php if ($realId): ?>
        <?php
            $orderData = $block->getOrderById($realId);
            $orderItems = $block->getOrderItems($realId);
        ?>
        <?= $block->getAdditionalInfoHtml() ?>

        <?php if ($orderData) : ?>
            <span class="briqpay-checkout-grand-total amount">
                <?= $orderData->formatPrice($orderData->getData('grand_total')) ?>
            </span>

            <div class="notes-container">
                <span class="note">
                    <?= __("Price including VAT"); ?>
                </span>
                <span class="note">
                    <?= __("You have chosen to pay by <b>{$block->getLatestPaymentMethod()}.</b>"); ?>
                </span>
            </div>

            <div class="order_inside">
                <ul class="briqpay-checkout-order-overview briqpay-checkout-thankyou-order-details order_details">
                    <li class="briqpay-checkout-order-overview__order order">
                        <?= __('Order number:') ?>
                        <strong>
                            <?php if ($block->getCanViewOrder()) : ?>
                                <p><?= __('%1', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
                            <?php else : ?>
                                <p><?= __('%1', $block->escapeHtml($block->getOrderId())) ?></p>
                            <?php endif; ?>
                        </strong>
                    </li>

                    <li class="briqpay-checkout-order-overview__date date">
                        <?= __('Date:') ?>
                        <strong>
                            <?php
                                $date = substr($orderData->getData('created_at'), 0, 10);
                            ?>
                            <?= date("F j, Y", strtotime($date)); ?>
                        </strong>
                    </li>
                    <li class="briqpay-checkout-order-overview__total total">
                        <?= __('Total:') ?>
                        <strong>
                            <span class="briqpay-checkout-Price-amount amount"><?= $orderData->formatPrice($orderData->getData('grand_total')) ?></span>
                        </strong>
                    </li>
                    <li class="briqpay-checkout-order-overview__payment-method method">
                        <?= __('Payment Method: ') ?> <strong><?= __('Briqpay Checkout') ?></strong>
                    </li>
                </ul>
            </div>

            <div class="logo-container">
                <img src="<?= $block->getViewFileUrl('Briqpay_Checkout::images/logo-dark.png'); ?>" alt="logo">
            </div>

            <?php if ($orderItems) : ?>
                <div class="briqpay-checkout-order__items">
                <strong><?= __('Order Details') ?></strong>
                <table>
                    <thead>
                    <tr>
                        <th class="col-item"><?= __('Product') ?></th>
                        <th class="col-subtotal"><?= __('Amount') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($orderItems as $orderItem) : ?>
                        <tr>
                            <td class="col-item product"><?= '<span>' . $orderItem->getData('name') . '</span>' . ' <span class="count"> x' . round($orderItem->getData('qty_ordered')) . ' </span >' ?></td>
                            <td class="col-amount"><?= $orderData->formatPrice($orderItem->getData('row_total_incl_tax')) ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <?php if ($orderData->getData('discount_amount') > 0) : ?>
                        <tr>
                            <td class="col-item"><?= __('Discount:') ?></td>
                            <td class="col-amount"><?= $orderData->formatPrice($orderData->formatPrice($orderData->getData('discount_amount'))) ?></td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <td class="col-item"><?= __('Shipping:') ?></td>
                        <td class="col-amount"><?= $orderData->formatPrice($orderData->getData('shipping_amount')) . ' <span class="count">(' . $orderData->getData('shipping_description') . ')</span >' ?></td>
                    </tr>
                    <tr>
                        <td class="col-item"><?= __('Payment Method: ') ?></td>
                        <td class="col-amount"><?= __('Briqpay Checkout') ?></td>
                    </tr>
                    <tr>
                        <td class="col-item"><?= __('Total') . ':' ?></td>
                        <td class="col-amount"><?= $orderData->formatPrice($orderData->getData('grand_total')) ?></td>
                    </tr>
                    </tbody>
                </table>
            <?php endif; ?>
        <?php endif; ?>
        </div>
    <?php endif; ?>
    <div class="actions-toolbar">
        <div class="briqpay-primary-wrapper">
            <a class="action briqpay-primary briqpay-btn continue" href="<?php /* @escapeNotVerified */
            echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */
                    echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
